---
abstract: 'Test a list of subroutines provided by a module'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  Carp: '0'
  Exporter: '0'
  ExtUtils::MakeMaker: '0'
  File::Spec::Functions: '0'
  List::Util: '0'
  Test::Builder::Tester: '1.18'
  Test::More: '0'
  version: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.140640'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-API
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Test::API:
    file: lib/Test/API.pm
    version: '0.004'
requires:
  Symbol: '0'
  Test::Builder::Module: '0.86'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/dagolden/Test-API/issues
  homepage: https://github.com/dagolden/Test-API
  repository: https://github.com/dagolden/Test-API.git
version: '0.004'
x_authority: cpan:DAGOLDEN
x_contributors:
  - 'Toby Inkster <mail@tobyinkster.co.uk>'
