---
name: Test-API
version: 0.002
author:
  - 'David Golden <dagolden@cpan.org>'
abstract: Test a list of subroutines provided by a module
license: apache
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Test-API
  repository: http://github.com/dagolden/Test-API/
requires:
  Devel::Symdump: 2.08
  Test::Builder::Module: 0.86
  base: 0
  perl: 5.006
build_requires:
  Carp: 0
  Test::Builder::Tester: 1.18
provides:
  Test::API:
    file: lib/Test/API.pm
    version: 0.002
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
